/**
 * Vite Plugin: LUT Inline Transform
 *
 * Transforms binary LUT files into inline shader/TypeScript code at build time.
 *
 * Usage in vite.config.ts:
 *   import { lutInlinePlugin } from './vite-plugin-lut-inline';
 *   plugins: [lutInlinePlugin({ lutDir: 'build/luts' })]
 *
 * Virtual modules:
 *   import { LUT_EXPONENTIAL, ... } from 'virtual:lut-wgsl';  // WGSL const arrays
 *   import { LUT_EXPONENTIAL, ... } from 'virtual:lut-glsl';  // GLSL const arrays
 *   import { DISPLACEMENT_LUTS } from 'virtual:lut-data';     // TS Float32Arrays
 */

import type { Plugin } from 'vite';
import { readFileSync, readdirSync } from 'fs';
import { join } from 'path';

export interface LutInlineOptions {
  /** Directory containing .r16f files */
  lutDir: string;
  /** Number of samples per LUT (default: 256) */
  samples?: number;
}

interface LutData {
  name: string;
  data: Float32Array;
}

/**
 * Read binary R16F file and convert to Float32Array
 */
function readR16F(filePath: string): Float32Array {
  const buffer = readFileSync(filePath);
  const view = new DataView(buffer.buffer, buffer.byteOffset, buffer.byteLength);
  const samples = buffer.length / 2;
  const result = new Float32Array(samples);

  for (let i = 0; i < samples; i++) {
    result[i] = float16ToFloat32(view.getUint16(i * 2, true));
  }

  return result;
}

/**
 * Convert float16 to float32
 */
function float16ToFloat32(h: number): number {
  const sign = (h >> 15) & 0x1;
  const exp = (h >> 10) & 0x1f;
  const mant = h & 0x3ff;

  if (exp === 0) {
    if (mant === 0) {
      return sign ? -0 : 0;
    }
    // Denormalized
    const e = -14;
    const m = mant / 1024;
    return (sign ? -1 : 1) * m * Math.pow(2, e);
  }

  if (exp === 31) {
    return mant ? NaN : (sign ? -Infinity : Infinity);
  }

  const e = exp - 15;
  const m = 1 + mant / 1024;
  return (sign ? -1 : 1) * m * Math.pow(2, e);
}

/**
 * Load all LUT files from directory
 */
function loadLuts(lutDir: string): LutData[] {
  const files = readdirSync(lutDir).filter(f => f.endsWith('.r16f'));
  return files.map(f => ({
    name: f.replace('.r16f', ''),
    data: readR16F(join(lutDir, f)),
  }));
}

/**
 * Generate WGSL shader code with embedded LUT arrays
 */
function generateWGSL(luts: LutData[]): string {
  const lines = [
    '// Auto-generated by vite-plugin-lut-inline',
    '// DO NOT EDIT',
    '',
    `const LUT_SAMPLES: u32 = ${luts[0]?.data.length ?? 256}u;`,
    '',
  ];

  for (const { name, data } of luts) {
    const constName = `LUT_${name.toUpperCase()}`;
    lines.push(`const ${constName}: array<f32, ${data.length}> = array<f32, ${data.length}>(`);

    // Format as rows of 8 values
    for (let i = 0; i < data.length; i += 8) {
      const row = Array.from(data.slice(i, i + 8))
        .map(v => v.toFixed(6))
        .join(', ');
      const comma = i + 8 < data.length ? ',' : '';
      lines.push(`    ${row}${comma}`);
    }
    lines.push(');');
    lines.push('');
  }

  // Add helper function
  lines.push('fn sampleLUT(lut: ptr<function, array<f32, LUT_SAMPLES>>, t: f32) -> f32 {');
  lines.push('    let clampedT = clamp(t, 0.0, 1.0);');
  lines.push('    let scaledT = clampedT * f32(LUT_SAMPLES - 1u);');
  lines.push('    let idx0 = u32(floor(scaledT));');
  lines.push('    let idx1 = min(idx0 + 1u, LUT_SAMPLES - 1u);');
  lines.push('    let frac = scaledT - floor(scaledT);');
  lines.push('    return mix((*lut)[idx0], (*lut)[idx1], frac);');
  lines.push('}');

  return lines.join('\n');
}

/**
 * Generate GLSL shader code with embedded LUT arrays
 */
function generateGLSL(luts: LutData[]): string {
  const samples = luts[0]?.data.length ?? 256;
  const lines = [
    '// Auto-generated by vite-plugin-lut-inline',
    '// DO NOT EDIT',
    '',
    `#define LUT_SAMPLES ${samples}`,
    '',
  ];

  for (const { name, data } of luts) {
    const constName = `LUT_${name.toUpperCase()}`;
    lines.push(`const float ${constName}[LUT_SAMPLES] = float[LUT_SAMPLES](`);

    for (let i = 0; i < data.length; i += 8) {
      const row = Array.from(data.slice(i, i + 8))
        .map(v => v.toFixed(6))
        .join(', ');
      const comma = i + 8 < data.length ? ',' : '';
      lines.push(`    ${row}${comma}`);
    }
    lines.push(');');
    lines.push('');
  }

  // Add helper function
  lines.push('float sampleLUT(float lut[LUT_SAMPLES], float t) {');
  lines.push('    float clampedT = clamp(t, 0.0, 1.0);');
  lines.push('    float scaledT = clampedT * float(LUT_SAMPLES - 1);');
  lines.push('    int idx0 = int(floor(scaledT));');
  lines.push('    int idx1 = min(idx0 + 1, LUT_SAMPLES - 1);');
  lines.push('    float frac = scaledT - floor(scaledT);');
  lines.push('    return mix(lut[idx0], lut[idx1], frac);');
  lines.push('}');

  return lines.join('\n');
}

/**
 * Generate TypeScript module with Float32Arrays
 */
function generateTypeScript(luts: LutData[]): string {
  const samples = luts[0]?.data.length ?? 256;
  const lines = [
    '// Auto-generated by vite-plugin-lut-inline',
    '// DO NOT EDIT',
    '',
    `export const LUT_SAMPLES = ${samples};`,
    '',
    `export type ProfileType = ${luts.map(l => `'${l.name}'`).join(' | ')};`,
    '',
    'export const PROFILE_NAMES: ProfileType[] = [',
    ...luts.map(l => `  '${l.name}',`),
    '];',
    '',
    'export const DISPLACEMENT_LUTS: Record<ProfileType, Float32Array> = {',
  ];

  for (const { name, data } of luts) {
    // Encode as base64 for compact representation
    const buffer = new Uint8Array(data.buffer);
    const base64 = Buffer.from(buffer).toString('base64');
    lines.push(`  ${name}: new Float32Array(Uint8Array.from(atob('${base64}'), c => c.charCodeAt(0)).buffer),`);
  }

  lines.push('};');
  lines.push('');

  // Add helper function
  lines.push('export function sampleLUT(profile: ProfileType, t: number): number {');
  lines.push('  const lut = DISPLACEMENT_LUTS[profile];');
  lines.push('  const clampedT = Math.max(0, Math.min(1, t));');
  lines.push('  const scaledT = clampedT * (LUT_SAMPLES - 1);');
  lines.push('  const idx0 = Math.floor(scaledT);');
  lines.push('  const idx1 = Math.min(idx0 + 1, LUT_SAMPLES - 1);');
  lines.push('  const frac = scaledT - idx0;');
  lines.push('  return lut[idx0] * (1 - frac) + lut[idx1] * frac;');
  lines.push('}');

  return lines.join('\n');
}

/**
 * Vite plugin factory
 */
export function lutInlinePlugin(options: LutInlineOptions): Plugin {
  const { lutDir } = options;
  let luts: LutData[] = [];

  const VIRTUAL_WGSL = 'virtual:lut-wgsl';
  const VIRTUAL_GLSL = 'virtual:lut-glsl';
  const VIRTUAL_DATA = 'virtual:lut-data';
  const RESOLVED_PREFIX = '\0';

  return {
    name: 'vite-plugin-lut-inline',
    enforce: 'pre',

    buildStart() {
      try {
        luts = loadLuts(lutDir);
        console.log(`[lut-inline] Loaded ${luts.length} LUT profiles from ${lutDir}`);
      } catch (e) {
        console.warn(`[lut-inline] Failed to load LUTs from ${lutDir}:`, e);
        luts = [];
      }
    },

    resolveId(id) {
      if (id === VIRTUAL_WGSL || id === VIRTUAL_GLSL || id === VIRTUAL_DATA) {
        return RESOLVED_PREFIX + id;
      }
      return null;
    },

    load(id) {
      if (luts.length === 0) {
        return null;
      }

      if (id === RESOLVED_PREFIX + VIRTUAL_WGSL) {
        return generateWGSL(luts);
      }

      if (id === RESOLVED_PREFIX + VIRTUAL_GLSL) {
        return generateGLSL(luts);
      }

      if (id === RESOLVED_PREFIX + VIRTUAL_DATA) {
        return generateTypeScript(luts);
      }

      return null;
    },
  };
}

export default lutInlinePlugin;
