/**
 * Combined Quadrant Shader
 *
 * Combines the core shader logic with LUT data at build time.
 * This module imports both pieces and concatenates them.
 */

// LUT constants (generated by scripts/generate-displacement-luts.mjs)
import LUT_DATA from '../../displacement/luts/generated-luts.wgsl';

// Core shader logic
import CORE_SHADER from './quadrant-core.frag.wgsl';

/**
 * Complete quadrant fragment shader with LUT data
 */
export const QUADRANT_FRAGMENT_SHADER = LUT_DATA + '\n' + CORE_SHADER;

export default QUADRANT_FRAGMENT_SHADER;
